"""Download the latin subsets of the site's typefaces and emit local @font-face CSS.

Run once (or when a weight is added):

    python3 tools/fetch_fonts.py

Writes deploy/fonts/*.woff2 and deploy/css/fonts.css. Self-hosting removes a
render-blocking third-party request and the privacy/availability dependency that
comes with it — the page can no longer be degraded by someone else's CDN.
"""

import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "deploy" / "fonts"
CSS_OUT = ROOT / "deploy" / "css" / "fonts.css"

# Chrome UA so Google serves woff2 rather than ttf.
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

# Deliberately minimal. Every extra weight is ~22-47 KB of latin subset that has
# to be justified by something the reader can actually see. 500 was dropped from
# Inter and JetBrains Mono: 400 and 600 cover every real use on the site.
FAMILIES = [
    ("Space Grotesk", "space-grotesk", "Space+Grotesk:wght@600;700"),
    ("Inter", "inter", "Inter:wght@400;600"),
    # 500 is kept: the mono labels are set in uppercase at small sizes, where
    # synthesized bold would smear. A real medium is worth the 20 KB.
    ("JetBrains Mono", "jetbrains-mono", "JetBrains+Mono:wght@400;500"),
]


def fetch(url):
    out = subprocess.run(
        ["curl", "-sS", "-A", UA, url],
        capture_output=True, check=True,
    )
    return out.stdout


def latin_blocks(css_text):
    """Yield (weight, style, url) for the latin subset only.

    Google emits a /* latin */ comment immediately before the matching
    @font-face block. Latin-ext, cyrillic and greek are dropped — the site is
    English and every extra subset is dead weight in the critical path.
    """
    parts = re.split(r"/\*\s*([a-z0-9-]+)\s*\*/", css_text)
    # parts = ['', subset, block, subset, block, ...]
    for i in range(1, len(parts) - 1, 2):
        subset, block = parts[i], parts[i + 1]
        if subset != "latin":
            continue
        weight = re.search(r"font-weight:\s*(\d+)", block)
        style = re.search(r"font-style:\s*(\w+)", block)
        url = re.search(r"url\((https://fonts\.gstatic\.com[^)]+\.woff2)\)", block)
        if weight and url:
            yield weight.group(1), (style.group(1) if style else "normal"), url.group(1)


def main():
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    faces = []

    for family, slug, spec in FAMILIES:
        url = f"https://fonts.googleapis.com/css2?family={spec}&display=swap"
        css = fetch(url).decode("utf-8")
        found = list(latin_blocks(css))
        if not found:
            print(f"  !! no latin subset found for {family}")
            return 1
        for weight, style, woff_url in found:
            name = f"{slug}-{weight}.woff2"
            data = fetch(woff_url)
            (FONT_DIR / name).write_bytes(data)
            print(f"  {name:<28} {len(data) / 1024:6.1f} KB")
            faces.append((family, weight, style, name))

    lines = [
        "/* Self-hosted latin subsets. Generated by tools/fetch_fonts.py —",
        "   do not edit by hand. font-display:swap keeps text visible during load. */",
        "",
    ]
    for family, weight, style, name in faces:
        lines.append(f"""@font-face {{
  font-family: '{family}';
  font-style: {style};
  font-weight: {weight};
  font-display: swap;
  src: url('/fonts/{name}') format('woff2');
}}""")
    CSS_OUT.write_text("\n".join(lines) + "\n")

    total = sum((FONT_DIR / n).stat().st_size for *_, n in faces)
    print(f"\nwrote {len(faces)} faces, {total / 1024:.1f} KB total -> {CSS_OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
